### ISSUE TITLE
masquerade, then session timeout; unable to return to prior url after re-login

### ISSUE THREAD

**Issue by davidlbean** [oivoodoo/devise_masquerade#53]
When masquerading (and using timeoutable) I visit a url only accessible to the masq'd user.  I walk away from the system, and it times out.  I return to the system by logging back in and devise tries to deliver me to the url I was at just prior to timing out...but that url isn't valid unless I'm masquerading.  Instead of the Rails error, I'd rather A) have my masquerading session restored or B) redirect to the root path with a flash message indicating I need to remasquerade to get back to the prior url.  Or perhaps I'm just missing something in my configuration?

I can dig into the source among devise, warden, timeoutable and masqueradable, but thought I'd see if someone knows how to address this before I do that...

Conditions:  
  - devise with timeoutable and masqueradable.  
  - user in masquerade visiting a path accessible to the masqueraded user (and not the original, base user)
  - devise times out
  - base user returns to the system and logs in
  - session is the base user's, not in the masqueraded user
  - after signin action tries to revisit the url that was current upon timeout...failure since that url is not reachable by the base user

rails 5.2.2.1
devise 4.6.1
devise_masquerade 0.6.5

Happy to stand up a little rails app that will demonstrate if that's helpful.

Many thanks!

**Comment by oivoodoo** [comment]
Hi @davidlbean . Sorry for long long delay to answer for this issue. to be honest I am thinking that it could be the issue that could be resolved by properly configured authorization gem or rescue for unauthorized exception on trying to access inaccessible url for the current user. 

Don't think masquerade part is related to the issue with devise sign in. `timeout` feature is internal part of devise and live without this gem at all. once you signed out because of timeout it starts again from the beginning to make sign in. 

As I see you could have situtation like:

- user A signed in to app `/A'
- user A has expired session now -> automatically log out
- user B signed in using the form to make sign in on timeout of user A, after sign in the recent route that you had `/A` but user B has no access there. it means failed on access this page.

Am I right?

**Comment by oivoodoo** [comment]
Going to close it for now. Don't think it's related to gem
