### ISSUE TITLE
You are already connected

### ISSUE THREAD

**Issue by GPif** [oivoodoo/devise_masquerade#66]
Try to make masquerade worked, but I keep having the "You are already connected" with my user not changing.

I am on dev, but I activated caches both with :
 * ```rails dev:cach```
 * ```touch /tmp/caching-dev.txt```

I also put in my ```environment.rb``` : ```Devise.masquerade_bypass_warden_callback=true```

How can I debug this ?

**Comment by oivoodoo** [comment]
Hi @GPif.

I would highly recommend in your local environment to place `pry` statements inside of the installed library in `masquerade` controller for example. it's pretty hard, for now, to find out how to help. one more way it would be to add an example ( demo ) project in Github and I can review it.

Thank you anyway for reporting!

**Comment by walterdavis** [comment]
Did something change in this area recently? I used this gem back in the 0.3.0 era, and I was able to proxy while currently logged in. Now, the only behavior I see is an alert that "You are already logged in", and my user doesn't change.

I see in the README that there is a configuration option `masquerade_bypass_warden_callback = true`. That appears to be what I want to invoke, in order to masquerade as a different user when I am currently logged in. But where does this go? Is it added to the Devise config initializer?

**Comment by walterdavis** [comment]
I just found [this issue](https://github.com/oivoodoo/devise_masquerade/issues/58), now closed, and while it explained a little more about how to enable caching (and intimated that this is all you need do) I did not find that to work here. Developing locally on my Mac, in Rails 6 and Devise 4.7.1. Every time I try to switch users I get the alert "You are already signed in" and my user doesn't change.

**Comment by walterdavis** [comment]
And I've just tested this in production, and it doesn't work there, either. So it's clearly not a caching issue.

**Comment by walterdavis** [comment]
Okay, sorry to keep banging on about this. I have pinned to ~>0.3.1 and got the behavior I expected. Clearly this was a design change, and I'd like to know (when you have a chance) why it was made. This works for me the way I expect it to on 0.3, even in Rails 6 and latest Devise. So that's a fine work-around for now. Thanks for building this gem!

**Comment by oivoodoo** [comment]
Hi @walterdavis . in the previous older versions I had the issue related to expiring tokens when masquerade was generated. when I fixed it everyone started to complain about it :)

I would love to keep expiration token, but I would say we can disable it in the dev environment by having true/false on specific config key depends on the environment. 

What do you think if I make it optionable to disable cache in the production environment?

**Comment by walterdavis** [comment]
Well, when I moved back to 0.3.0, my use case suddenly started working as I expected. But my real underlying question is this: is my use-case no longer supported? Here's how I have used Masquerade in the past, for several high-profile projects:

1. The option is only shown to admins, so you have to be logged in to see it at all.
2. While you are logged in as you admin-self, you see an option in your user menu to "proxy" as another user. Clicking this opens a Bootstrap modal with a picking list populated with all users besides yourself.
3. Choosing a person from that list, and clicking the Proxy button, navigates you to `/users/masquerade/:id`.
4. You are now acting as the other person, a banner appears on the screen warning you of the fact, and you have a new option in your user menu to end the proxy.

So this is fundamentally different than your README's suggestion of having a number of links that can log you in *from a logged-out state* as a specific person, without needing to know their password. 

I totally get what that means, from a Warden standpoint and as a workflow. But since I am accustomed to using (perhaps abusing) your gem to provide a sort of "let me see the problem you're having, through your eyes" support tool, and since I want to use it in production, and therefore restrict its use to logged-in, credentialed users, I am wondering if the latest version of your gem can be coerced into behaving the way that older versions did.

If it can't, do you know at what point that stopped being possible? What is the newest *old* version that still works the way I expect it to?

**Comment by GPif** [comment]
As suggested, I tried to rollback to the 0.3.0 version, but it changed nothing.

I investigated a bit further, and it turned out that the problem is due to the fact we use slug for our user.
So calling ```masquarade_path(@user)``` end up to call ```/user/masquarade/wired_id_created_by_slug```. So, to work around, i changed the code to ```user_masquarade_path(@user.id)``` to force the call with the id.

**Comment by mvz** [comment]
@walterdavis Your use case is exactly my use case, and I got it working with the latest version. The important two things to do are:
- Make sure caching is enabled
- Do not use the `user_masquerade_path` or similar that matches the route, but instead use `masquerade_path`, which will create a path with an included token.

**Comment by walterdavis** [comment]
Thanks! I will definitely try that. Is there a config key to "enable caching" in production?

Walter

**Comment by mvz** [comment]
> Is there a config key to "enable caching" in production?

That's just standard Rails caching and should be enabled automatically in production.

**Comment by drkelly58** [comment]
I'm having the same issue. Had everything in place and working a while back in our dev replica, decided to hold off for a while to deploy. Now when I add everything back it doesn't work. Caching is on, and it's the same version of the Gem in both.
Only big change I can think of is that Rails was updated to 6.

Any ideas of what to check?

**Comment by gbayless** [comment]
first writing one of these so bear with me.

it seems to be an issue with the latest change 'introduce secure way by passing for masquerade routes tokens'

using pry I found the following:

from "def find_resource"
`masqueraded_resource_class.to_adapter.find_first(id: params[:id])`
this returns a valid user.

however 
`masqueraded_resource_class.find_by_masquerade_key(params[Devise.masquerade_param]).where(id: params[:id]).first`
this returns nil

`params[Devise.masquerade_param] `
returns nil 

`Devise.masquerade_param`
returns "masquerade"

`find_by_masquerade_key`
get a nil key

Some extra info:
my params:
`=> <ActionController::Parameters {"controller"=>"devise/masquerades", "action"=>"show", "id"=>"198"} permitted: false>`

**Comment by gbayless** [comment]
Doing some further digging:

I have a 4.1 app with masquerade working on 0.4
There is also a cache file users<random_string>masquerade 
but I don't see one of those on my Rails 5.2 app.

`[6] pry(User)> ::Rails.cache.write(cache_key, id, expires_in: Devise.masquerade_expires_in)`

`Errno::ENOTDIR: Not a directory @ rb_file_s_rename - (/home/deploy/DSM/tmp/cache/.00020201024-5155-1r05fr0, /home/deploy/DSM/tmp/cache/001/000/)
from ~/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.4/lib/active_support/core_ext/file/atomic.rb:50:in `rename'`

But I am not sure what to make of this or how to fix it. I do see some changes related to this code in "finalize the changes for rails 5+ upgrade" commit.

**Comment by gbayless** [comment]
Doing some further digging:

I have a 4.1 app with masquerade working on 0.4
There is also a cache file users<random_string>masquerade
but I don't see one of those on my Rails 5.2 app.

[6] pry(User)> ::Rails.cache.write(cache_key, id, expires_in: Devise.masquerade_expires_in)

Errno::ENOTDIR: Not a directory @ rb_file_s_rename - (~/app/tmp/cache/.00020201024-5155-1r05fr0, ~/app/tmp/cache/001/000/) from ~/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4.4/lib/active_support/core_ext/file/atomic.rb:50:in rename'`

But I am not sure what to make of this or how to fix it. I do see some changes related to this code in "finalize the changes for rails 5+ upgrade" commit.

**Comment by oivoodoo** [comment]
@gbayless could you share the link that you used to request `"action"=>"show"`? Probably `params` should permit passed token, but it would be great if you share the example of the link to verify that you are passing at least it properly. Remember that you should have cache enabled to use the gem. it's using expires at on token fields to reduce the possibility to share the link or to have copied link.

**Comment by gbayless** [comment]
Sure thing

View:
`<%= select_tag :login_as_users, options_for_select(@login_as_users.collect{|u| [u.full_name, u.id]}), {include_blank: "Select Engineer", :onchange => "dosmth(this.value)"} %>`

JS:

`window.dosmth = function(val) {`
`  console.log(val);`
`  location.href = '/users/masquerade/' + val; `
`}`


Routes:

`rails routes | grep masqu`
`back_user_masquerade_index GET      /users/masquerade/back(.:format)  devise/masquerades#back`
`user_masquerade GET      /users/masquerade/:id(.:format) devise/masquerades#show`

**Comment by gbayless** [comment]
Would a caching issue explain the lack in masquerade params?

**Comment by gbayless** [comment]
I think I see what is happening:

If I add '= link_to "Login As", masquerade_path(user)' in the view. The before_action is triggered.
The JS method I am using does not trigger the before_action.

Not sure the best method to re-write this but I am sure I will figure it out if I keep at it.

**Comment by oivoodoo** [comment]
@gbayless to be honest I don't understand how `before_action` could be related to JS. the params look good, probably you extend masquerade controller and missed something there to implement. it's hard to say for now.
