### ISSUE TITLE
Undefined method 'prepend_before_filter' for Devise::MasqueradesController:Class Did you mean? prepend_before_action

### ISSUE THREAD

**Issue by thejunaidiqbal1** [oivoodoo/devise_masquerade#97]
I've an issue when I used this gem.
I used in gem file gem `'devise_masquerade', '~> 0.2.0'` and same issued with `gem 'devise_masquerade'`. So what should I do? I didn't create any method like this but I don't know where is this and my trace error is:
`devise_masquerade (0.2.0) app/controllers/devise/masquerades_controller.rb:2:in <class:MasqueradesController>'`

**Comment by oivoodoo** [comment]
@thejunaidiqbal1 what the version do you have in your Gemfile.lock for devise_masquerade as result after bundle install?

**Comment by thejunaidiqbal1** [comment]
@oivoodoo my result is on gemfile.lock are:
    devise_masquerade (1.3.9)
      devise (>= 4.7.0)
      globalid (>= 0.3.6)
      railties (>= 5.2.0)

**Comment by thejunaidiqbal1** [comment]
@oivoodoo  my result is on gemfile.lock are:
devise_masquerade (1.3.9)
devise (>= 4.7.0)
globalid (>= 0.3.6)
railties (>= 5.2.0)

**Comment by thejunaidiqbal1** [comment]
@oivoodoo  one more thing is that if I have installed a devise_masquerade with version 1.3.9 then when I check my routes on users so these type of routes I'll show, so where I passed my user because it showed me like index instead of show, as shown in image:

![image](https://user-images.githubusercontent.com/85728756/139808179-4cd8f75d-70c9-40dd-865e-43a089198cd8.png)

**Comment by oivoodoo** [comment]
Hi @thejunaidiqbal1 

Not sure why you have the error with `prepend_before_filter` because in the masquerade controller it has only `prepend_before_action` adopting to the latest rails versions.

I could imagine the problem like that:

- you have running rails server (with spring)
- you have just installed the old version 0.2.0
- then you decided to make the upgrade of the gem to 1.3.9
- then you opened again the pages with masquerade button
- pressed the button and used the cached classes for masquerade controller.


Please check the example dummy app inside of the spec folder in the library:

https://github.com/oivoodoo/devise_masquerade/blob/master/spec/dummy/app/views/layouts/application.html.erb

https://github.com/oivoodoo/devise_masquerade/blob/master/spec/dummy/app/views/users/_user.html.erb

ensure to have the `rails dev:cache` because the library internally using cache to store temporary user details.
