### ISSUE TITLE
Always showing a message that "already signed".

### ISSUE THREAD

**Issue by thejunaidiqbal1** [oivoodoo/devise_masquerade#98]
@oivoodoo 
I'm using version of this gem is 1.3.9. I've two devise installed on my project; Admin and User. So I mentioned `:masqueradable` in `User.rb` (and if I mentioned on both models Admin.rb and User.rb but same issue). And also mentioned these lines in `devise.rb`: 
  
  `config.masquerade_param = 'masquerade'`
  `config.masquerade_expires_in = 1.hour`
  `config.masquerade_key_size = 16 `
  `config.masquerade_bypass_warden_callback = false`
  `config.masquerading_resource_class = AdminUser`
  `config.masquerading_resource_name = :admin_user`
  `config.masqueraded_resource_class = User`
  `config.masqueraded_resource_name = :user`

Even if I removed these lines or just type these 4 lines (`config.masquerading_resource_class = AdminUser`, `config.masquerading_resource_name = :admin_user`, `config.masqueraded_resource_class = User`, `config.masqueraded_resource_name = :user`), same error occurred. 
One more thing so I found some solution that create a controller for masquerade same as on doc of this gem on github, and mentioned routes on `routes` file, same error occurred. 
I already read [closed issue](https://github.com/oivoodoo/devise_masquerade/issues/58), but same error occurred, so let me know please what should I do?

One more thing is that I also run this (`rails dev:cache`) for enabling because my user_masquerade? is always show false. 
If I checked on my routes it show me like this:
`user_masquerade_index` for devise/masquerades#show
and
`admin_user_masquerade_index` for admin_users/masquerades#show

**Comment by oivoodoo** [comment]
Hi, @thejunaidiqbal1 Do you have the custom implementation for the masquerade controller? 

Please check spec/dummy for examples of how to use `Student` and `User` models, probably it would be helpful. I have the integration test cases to cover the standard usage of the masquerading process.

if it doesn't help, I could help to debug it but it would require having the demo app, debug yourself by using cloning devise_masquerade project into the local folder and specifying in Gemfile -> `gem 'devise_masquerade', path: "your_local_path/devise_masquerade"` and place there `require 'pry' ; binding.pry` inside of the masquerade controller for actions `show` and `back`, or we could have the call to debug your app because it's pretty rare çase for me (but it would require to find out when I have the time and match together with the timezone).  


Let me know how it goes with research, in case if you see the possible issues please submit or PR or describe it I will cover it myself.

Thanks!

**Comment by thejunaidiqbal1** [comment]
Hello @oivoodoo,
Thanks for your replying and helping. I've added `require 'pry' ; binding.pry` in masquerades controller. So at this time when I clicked on "Login As", so my console showed me some thing like this as shown in image:
![image](https://user-images.githubusercontent.com/85728756/140499314-4d176dc3-babc-447b-94cc-8e87a2fc18d0.png)

**Comment by thejunaidiqbal1** [comment]
@oivoodoo kindly response me on my issue please!

**Comment by oivoodoo** [comment]
@thejunaidiqbal1 in your screenshot you placed the debug code inside of the controller instead of the action.
